---
# This playbook installs mysql on a windows hosts

- name: install MariaDB on a windows host
  hosts: role_dbserver:&windows
  vars_files:
    files/winrm_vars.yml

  tasks:

  - name: Install MariaDB
    win_chocolatey:
      name: "mariadb"
      state: present

  - name: Enable Host Based Firewall
    win_firewall:
      state: enabled

  - name: Define Host Based Firewall rule to allow http on TCP port 3306
    win_firewall_rule:
      name: http
      localport: 3306
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes

      
  - name: Report end points
    debug:
      msg: "RDP at {{ public_ip }}"
