---
# This playbook deploys the db

- name: Deploy db
#  hosts: localhost    
  hosts: role_dbserver
  vars_files:
    winrm_vars.yml
  tasks:
#  - name: create DB
#    mysql_db:
#      login_host: 168.63.109.207
#      name: "testdb"
#      login_user: "dbuser"
#      login_password: "password"
  
  - name: copy mysql prep to host
    win_template:
      src: prepmysql.sql.j2
      dest: C:\Windows\Temp\prepmysql.sql
      
  - name: prep mysql on host for remote access
    win_shell: 'mysql -u root --password="r3dh4t1!" < C:\Windows\Temp\prepmysql.sql'
