---
# This playbook deploys the website

- name: Deploy web site
  hosts: role_webserver:&windows
  vars_files:
  - files/winrm_vars
  - files/database_credentials
  vars:
    dbserver: "{{ groups['role_dbserver'][0] }}"

  tasks:
  - name: Purge website files from directory
    win_file:
      path: C:\inetpub\wwwroot\
      state: absent

  - name: check out website from git
    win_command: git clone https://github.com/fvzwieten/simple_db_app.git C:\inetpub\wwwroot
    args:
      chdir: C:\Program Files\Git\bin
 
  - name: define config for website 
    win_template:
      src: files/config.php.j2
      dest: C:\inetpub\wwwroot\config.php
      
  - name: Report IP endpoint
    debug:
      msg: "RDP and Website at {{ public_ip }}"
