---
# This playbook deploys the website

- name: Deploy web site
  hosts: role_webserver
  vars_files:
    winrm_vars.yml    

  tasks:

  # Remove Default Web Site and the standard port 80 binding
  - name: Remove Default Web Site
    win_iis_website:
      name: "Default Web Site"
      physical_path: C:\inetpub\wwwroot
      state: stopped

  # Remove Web Site and the standard port 80 binding
#  - name: Remove Web Site
#    win_iis_website:
#      name: "Acme"
#      state: absent

  - name: Purge website files from directory
    win_file:
      path: C:\inetpub\wwwroot\
      state: absent

#  - name: Create the website in IIS
#    win_iis_website:
#      name: Acme
#      state: started
#      port: 80
#      ip: 127.0.0.1
#      hostname: acme.local
#      application_pool: acme
#      physical_path: C:\inetpub\acme\html
#      parameters: logfile.directory:C:\inetpub\acme\log
#    register: website

  - name: check out website from git
    win_command: git clone https://github.com/fvzwieten/simple_db_app.git C:\inetpub\wwwroot
    args:
      chdir: C:\Program Files\Git\bin
      
  - name: Remove Default Web Site
    win_iis_website:
      name: "Default Web Site"
      physical_path: C:\inetpub\wwwroot
      state: started

