---
# This playbook deploys the db

- name: Deploy db
  hosts: role_dbserver:&windows
  vars_files:
  - files/winrm_vars
  - files/database_credentials

  tasks:
  - name: copy mysql schema file to host
    win_template:
      src: files/schema.sql.j2
      dest: C:\Windows\Temp\schema.sql

  - name: configure MariaDB on host for web app
    win_shell: 'mysql -u root < C:\Windows\Temp\schema.sql'
    args:
      executable: cmd
      
 - name: Report end points
   debug:
     msg: "RDP at {{ public_ip }}"
