---
# This playbook installs and enables IIS on Windows hosts with php and mysql support

- name: install IIS including php and mysql support
  hosts: role_webserver
  vars_files:
    winrm_vars.yml
    
  tasks:
  - name: Install Web-Server
    win_feature:
      name: Web-Server
      state: present
      include_sub_features: yes
      include_management_tools: yes
    register: win_feature

  - name: Enable firewall
    win_firewall:
      state: enabled

  - name: Firewall rule to allow http on TCP port 80
    win_firewall_rule:
      name: http
      localport: 80
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes

  - name: Firewall rule to allow https on TCP port 443
    win_firewall_rule:
      name: http
      localport: 443
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes
      
  - name: install php
    win_chocolatey:
      name: "{{ item }}"
      state: present
    loop:
     - git
     - webpicmd
     - lessmsi

  - name: install php using Web Platform Installer
    win_webpicmd:
      name: PHP72

  - name: reboot if installing feature requires it
    win_reboot:
    when: win_feature.reboot_required
