---
# This playbook deploys the website

- name: Deploy web site
  hosts: role_webserver
  vars_files:
    winrm_vars.yml    

  tasks:
  - name: check out website from git
    win_shell:
      'C:\Program Files\Git\bin\git.exe' clone 'https://github.com/fvzwieten/simple_db_app.git' 'C:\inetpub\wwwroot'
