---
# this playbook promotes a windows server to a domain controller
# It depend on external (extra) vars to supply the domain name and the safe_mode_password
- name: promote server to a Domain Controller
  hosts: role_dcserver
  vars_files:
    files/winrm_vars

  tasks:
  - name: create domain controller
    win_domain:
      dns_domain_name: "{{ domain_name }}"
      safe_mode_password: "{{ password }}"
    register: domain_result
    
  - name: export domain name
    set_stats:
      data:
        domain_name: "{{ domain_name }}"

  - name: reboot after creating domain
    win_reboot:
    when: domain_result.reboot_required
    
  - name: Wait for the Kerberos port to come online
    wait_for:
      port: 53
      host: '{{ private_ip }}'
      timeout: 300
