---
# This playbook installs mysql on a windows hosts

- name: install mariadb on a windows host
  hosts: role_dbserver
  vars_files:
    winrm_vars.yml
    
  tasks:
  - name: remove mysql
    win_chocolatey:
      name: "mysql"
      state: absent

  - name: install mariadb
    win_chocolatey:
      name: "mariadb"
      state: present

  - name: Enable firewall
    win_firewall:
      state: enabled

  - name: Firewall rule to allow http on TCP port 80
    win_firewall_rule:
      name: http
      localport: 3306
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes

  - name: Start de mysql service
    win_service:
      name: mysql
      start_mode: auto
      state: started
