---
# This playbook deploys the db

- name: Deploy db
#  hosts: localhost    
  hosts: role_dbserver
  vars_files:
    winrm_vars.yml
  tasks:
  
  - name: copy mysql prep file to host
    win_template:
      src: prepmysql.sql.j2
      dest: C:\Windows\Temp\prepmysql.sql

  - name: prep mysql on host for remote access
    win_shell: 'mysql -u root < C:\Windows\Temp\prepmysql.sql'
    args:
      executable: cmd
