---
# This playbook deploys the website

- name: Deploy web site
  hosts: role_webserver
  vars_files:
    winrm_vars.yml    

  tasks:
  - name: Purge website files from directory
    win_file:
      path: C:\inetpub\wwwroot\
      state: absent

  - name: check out website from git
    win_command: git clone https://github.com/fvzwieten/simple_db_app.git C:\inetpub\wwwroot
    args:
      chdir: C:\Program Files\Git\bin
 

